### ISSUE TITLE
Update error status code returned to dispatcher for indexing failures

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/base_indexer#33]

**Comment by lmcglohon** [comment]
The error should be logged with the timestamp of the reporting, the druid it tried to delete, the target (indexing service) name and the subtarget (solr index) it failed to delete it from.

**Comment by mejackreed** [comment]
Ok .. but what should the response be to the dispatcher (or other requestor). Currently it just returns a 202 on all errors.

**Comment by lmcglohon** [comment]
I would expect the response to be "503 Service Unavailable" @drh-stanford Do you know of any other expected error codes?

**Comment by drh-stanford** [comment]
yeah i just commented on this too and looked into it a bit. I'd use `500 Internal Server Error` rather than any 2xx status code. `503` would be good if the error is connection related. The guidelines are lame:

> an appropriate error response SHOULD be given that reflects the nature of the problem

**Comment by mejackreed** [comment]
My concern here is that we are returning the same status code regardless of what happens. Some targets may get indexed or deleted, some might not. No targets may get deleted. The idea here is we don't know. Should the status code reflect that?

**Comment by peetucket** [comment]
Typically we are doing one API call per druid, often for one (or at most two) targets.  A delete call may spawn multiple target calls.  Since any of those calls should be replayable with no consequences (i.e. you can easily re-index or re-delete from a certain target/druid , even if the first one happened to have succeeded), it may not be worth the trouble trying to build in tracking of errors at the target level.  Basically for logging the operation succeeds or fails as a transaction at the druid level, even if the underlying operations are not truly transactional.
